[package]
name = "syssonic"
version = "0.1.0"
edition = "2021"

[dependencies]
tunes = "0.5.0"
anyhow = "1.0"
sysinfo = "0.31"
tokio = { version = "1.35", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
